//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Nexus AOT Binder Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Nexus.Core;
using Nexus.Netcode;

namespace Nexus.Generated
{
    public static class NexusGeneratedBinder
    {
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.SubsystemRegistration)]
        public static void Initialize()
        {
        }

        // Forces IL2CPP to preserve members that are injected
        public static void PreserveMembers()
        {
            #pragma warning disable 0169, 0414, 0219
            if (false)
            {
            }
            #pragma warning restore 0169, 0414, 0219
        }
    }
}
