using System;
using System.IO;
using NUnit.Framework;
using UnityEditor;
using Nexus.Editor;

namespace Nexus.Editor.Tests
{
    // Locks the P1-B build-wiring contract: the AOT binder must regenerate automatically
    // before a build (so a stale binder never ships in an IL2CPP build), and the
    // NEXUS_DISABLE_AUTOGEN opt-out must skip that regeneration without breaking the build.
    [TestFixture]
    public class BuildWiringTests
    {
        private string _binderPath;
        private string _linkXmlPath;
        private string _prevDisableAutogen;
        private string _prevDisableValidation;
        private bool _binderExisted;
        private string _originalBinder;
        private bool _linkXmlExisted;
        private string _originalLinkXml;

        [SetUp]
        public void SetUp()
        {
            var settings = NexusEditorSettings.GetOrCreateSettings();
            _binderPath = Path.Combine(settings.BinderOutputPath, "NexusGeneratedBinder.g.cs");
            _linkXmlPath = Path.Combine(settings.LinkXmlOutputPath, "link.xml");

            // These outputs are intentionally git-ignored and are mutated by the tests.
            // Snapshot both before each test so a guard test cannot leave a stale/custom
            // link.xml (or a deleted binder) behind for the next test/build.
            _binderExisted = File.Exists(_binderPath);
            _originalBinder = _binderExisted ? File.ReadAllText(_binderPath) : null;
            _linkXmlExisted = File.Exists(_linkXmlPath);
            _originalLinkXml = _linkXmlExisted ? File.ReadAllText(_linkXmlPath) : null;

            // Start each test from a generator-owned empty state.  A stale hand-curated
            // link.xml must not make the ordinary generation tests fail before they can
            // exercise their own assertions; TearDown restores the exact pre-test files.
            if (File.Exists(_binderPath)) File.Delete(_binderPath);
            if (File.Exists(_linkXmlPath)) File.Delete(_linkXmlPath);

            _prevDisableAutogen = Environment.GetEnvironmentVariable("NEXUS_DISABLE_AUTOGEN");
            _prevDisableValidation = Environment.GetEnvironmentVariable("NEXUS_DISABLE_VALIDATION");
            Environment.SetEnvironmentVariable("NEXUS_DISABLE_AUTOGEN", null);
            Environment.SetEnvironmentVariable("NEXUS_DISABLE_VALIDATION", null);
        }

        [TearDown]
        public void TearDown()
        {
            Environment.SetEnvironmentVariable("NEXUS_DISABLE_AUTOGEN", _prevDisableAutogen);
            Environment.SetEnvironmentVariable("NEXUS_DISABLE_VALIDATION", _prevDisableValidation);
            RestoreFile(_binderPath, _binderExisted, _originalBinder);
            RestoreFile(_linkXmlPath, _linkXmlExisted, _originalLinkXml);
        }

        private static void RestoreFile(string path, bool existed, string content)
        {
            if (existed)
            {
                File.WriteAllText(path, content ?? string.Empty);
            }
            else if (File.Exists(path))
            {
                File.Delete(path);
            }
        }

        [Test]
        public void GenerateBinder_WritesAutoGeneratedBinderAndLinkXml()
        {
            Assert.DoesNotThrow(() => NexusCodeGenerator.GenerateBinder(),
                "GenerateBinder() should run without throwing in a healthy project.");

            Assert.IsTrue(File.Exists(_binderPath), $"Expected AOT binder at {_binderPath}");
            var binder = File.ReadAllText(_binderPath);
            Assert.That(binder, Does.Contain("<auto-generated>"),
                "Binder must carry the <auto-generated> tag (overwrite-guard contract).");
            Assert.That(binder, Does.Contain("NexusGeneratedBinder"),
                "Binder must contain the generated injector class.");

            Assert.IsTrue(File.Exists(_linkXmlPath),
                $"Expected IL2CPP preservation file at {_linkXmlPath}");
            var xml = File.ReadAllText(_linkXmlPath);
            Assert.That(xml, Does.Contain("<auto-generated>"),
                "Generated link.xml must carry the overwrite-guard marker.");
            Assert.That(xml, Does.Contain("preserve=\"all\""),
                "link.xml must preserve generated injectee types under IL2CPP stripping.");
        }

        [Test]
        public void OnPreprocessBuild_RegeneratesBinderBeforeValidation()
        {
            // Isolate the binder-regeneration behavior by bypassing the validation pass.
            Environment.SetEnvironmentVariable("NEXUS_DISABLE_VALIDATION", "1");
            if (File.Exists(_binderPath)) File.Delete(_binderPath);

            var preProcessor = new NexusBuildPreProcessor();
            Assert.DoesNotThrow(() => preProcessor.OnPreprocessBuild(null),
                "Build pre-processor must run without throwing when autogen is enabled.");

            Assert.IsTrue(File.Exists(_binderPath),
                "OnPreprocessBuild must regenerate the AOT binder even if the file was deleted.");
            var binder = File.ReadAllText(_binderPath);
            Assert.That(binder, Does.Contain("<auto-generated>"),
                "The regenerated binder must still be a valid auto-generated file.");
        }

        [Test]
        public void OnPreprocessBuild_SkipsBinderWhenAutogenDisabled()
        {
            Environment.SetEnvironmentVariable("NEXUS_DISABLE_AUTOGEN", "1");
            Environment.SetEnvironmentVariable("NEXUS_DISABLE_VALIDATION", "1");
            if (File.Exists(_binderPath)) File.Delete(_binderPath);

            var preProcessor = new NexusBuildPreProcessor();
            Assert.DoesNotThrow(() => preProcessor.OnPreprocessBuild(null),
                "Build pre-processor must still run when autogen is opted out.");

            Assert.IsFalse(File.Exists(_binderPath),
                "NEXUS_DISABLE_AUTOGEN must skip binder regeneration during the build.");
        }

        [Test]
        public void LinkXml_OverwriteGuard_ProtectsNonAutoGeneratedFiles()
        {
            // Write a hand-curated link.xml (no <auto-generated> tag).
            string customContent = "<linker>\n  <assembly fullname=\"CustomAssembly\"><type fullname=\"CustomType\" preserve=\"all\" /></assembly>\n</linker>";
            File.WriteAllText(_linkXmlPath, customContent);
            string binderBefore = File.Exists(_binderPath) ? File.ReadAllText(_binderPath) : null;

            // Run codegen: it must fail loudly instead of silently allowing an IL2CPP
            // build to proceed with stale preservation rules.
            var ex = Assert.Throws<InvalidOperationException>(() => NexusCodeGenerator.GenerateBinder());
            StringAssert.Contains("Overwrite blocked", ex.Message);

            string afterGen = File.ReadAllText(_linkXmlPath);
            Assert.That(afterGen, Is.EqualTo(customContent),
                "link.xml without <auto-generated> tag must NOT be overwritten by codegen.");
            string binderAfter = File.Exists(_binderPath) ? File.ReadAllText(_binderPath) : null;
            Assert.That(binderAfter, Is.EqualTo(binderBefore),
                "A blocked link.xml must fail before the paired binder is changed.");
        }

        [Test]
        public void LinkXml_AutoGeneratedContent_CanBeOverwritten()
        {
            // Write a link.xml WITH the <auto-generated> tag.
            string autoContent = "<!-- <auto-generated> -->\n<linker>\n  <assembly fullname=\"TestAsm\"><type fullname=\"TestType\" preserve=\"all\" /></assembly>\n</linker>";
            File.WriteAllText(_linkXmlPath, autoContent);

            // Run codegen: it SHOULD overwrite (file has <auto-generated>).
            NexusCodeGenerator.GenerateBinder();

            string afterGen = File.ReadAllText(_linkXmlPath);
            Assert.That(afterGen, Does.Not.Contain("TestType"),
                "link.xml with <auto-generated> tag must be overwritten by codegen.");
            Assert.That(afterGen, Does.Contain("<auto-generated>"),
                "Generated link.xml must carry the <auto-generated> tag.");
        }
    }
}
