using System;
using System.IO;
using NUnit.Framework;
using UnityEditor;
using Nexus.Editor;

namespace Nexus.Editor.Tests
{
    // Locks the P1-B build-wiring contract: the AOT binder must regenerate automatically
    // before a build (so a stale binder never ships in an IL2CPP build), and the
    // NEXUS_DISABLE_AUTOGEN opt-out must skip that regeneration without breaking the build.
    [TestFixture]
    public class BuildWiringTests
    {
        private string _binderPath;
        private string _linkXmlPath;
        private string _prevDisableAutogen;
        private string _prevDisableValidation;

        [SetUp]
        public void SetUp()
        {
            var settings = NexusEditorSettings.GetOrCreateSettings();
            _binderPath = Path.Combine(settings.BinderOutputPath, "NexusGeneratedBinder.g.cs");
            _linkXmlPath = Path.Combine(settings.LinkXmlOutputPath, "link.xml");

            _prevDisableAutogen = Environment.GetEnvironmentVariable("NEXUS_DISABLE_AUTOGEN");
            _prevDisableValidation = Environment.GetEnvironmentVariable("NEXUS_DISABLE_VALIDATION");
            Environment.SetEnvironmentVariable("NEXUS_DISABLE_AUTOGEN", null);
            Environment.SetEnvironmentVariable("NEXUS_DISABLE_VALIDATION", null);
        }

        [TearDown]
        public void TearDown()
        {
            Environment.SetEnvironmentVariable("NEXUS_DISABLE_AUTOGEN", _prevDisableAutogen);
            Environment.SetEnvironmentVariable("NEXUS_DISABLE_VALIDATION", _prevDisableValidation);
            // Always restore a correct binder so the project is never left without one.
            NexusCodeGenerator.GenerateBinder();
        }

        [Test]
        public void GenerateBinder_WritesAutoGeneratedBinderAndLinkXml()
        {
            Assert.DoesNotThrow(() => NexusCodeGenerator.GenerateBinder(),
                "GenerateBinder() should run without throwing in a healthy project.");

            Assert.IsTrue(File.Exists(_binderPath), $"Expected AOT binder at {_binderPath}");
            var binder = File.ReadAllText(_binderPath);
            Assert.That(binder, Does.Contain("<auto-generated>"),
                "Binder must carry the <auto-generated> tag (overwrite-guard contract).");
            Assert.That(binder, Does.Contain("NexusGeneratedBinder"),
                "Binder must contain the generated injector class.");

            if (File.Exists(_linkXmlPath))
            {
                var xml = File.ReadAllText(_linkXmlPath);
                Assert.That(xml, Does.Contain("<linker>"),
                    "link.xml must be present to preserve injectors under IL2CPP stripping.");
            }
        }

        [Test]
        public void OnPreprocessBuild_RegeneratesBinderBeforeValidation()
        {
            // Isolate the binder-regeneration behavior by bypassing the validation pass.
            Environment.SetEnvironmentVariable("NEXUS_DISABLE_VALIDATION", "1");
            if (File.Exists(_binderPath)) File.Delete(_binderPath);

            var preProcessor = new NexusBuildPreProcessor();
            Assert.DoesNotThrow(() => preProcessor.OnPreprocessBuild(null),
                "Build pre-processor must run without throwing when autogen is enabled.");

            Assert.IsTrue(File.Exists(_binderPath),
                "OnPreprocessBuild must regenerate the AOT binder even if the file was deleted.");
            var binder = File.ReadAllText(_binderPath);
            Assert.That(binder, Does.Contain("<auto-generated>"),
                "The regenerated binder must still be a valid auto-generated file.");
        }

        [Test]
        public void OnPreprocessBuild_SkipsBinderWhenAutogenDisabled()
        {
            Environment.SetEnvironmentVariable("NEXUS_DISABLE_AUTOGEN", "1");
            Environment.SetEnvironmentVariable("NEXUS_DISABLE_VALIDATION", "1");
            if (File.Exists(_binderPath)) File.Delete(_binderPath);

            var preProcessor = new NexusBuildPreProcessor();
            Assert.DoesNotThrow(() => preProcessor.OnPreprocessBuild(null),
                "Build pre-processor must still run when autogen is opted out.");

            Assert.IsFalse(File.Exists(_binderPath),
                "NEXUS_DISABLE_AUTOGEN must skip binder regeneration during the build.");
        }
    }
}
