using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using NUnit.Framework;
using Nexus.Editor;
using UnityEditor;
using UnityEngine;

namespace Nexus.Tests.Editor
{
    /// <summary>
    /// Locks the sample↔wizard sync contract end to end. Four layers:
    /// 1) <c>NexusSetupWizard.GeneratedFiles</c> — the mapping the wizard claims it
    ///    generates — must match the canonical <c>Assets/Scripts/Game/Samples</c> files
    ///    byte-for-byte (line-ending normalized);
    /// 2) the real generation write path (<c>WriteGeneratedFiles</c>, the exact code
    ///    <c>GenerateAllCode</c> calls) must produce those bytes in a fresh directory;
    /// 3) the generated sources must COMPILE with the Roslyn compiler Unity ships,
    ///    against the real UnityEngine + com.nexus.core reference assemblies;
    /// 4) the SHA-256 content hash of every generated file must be the one documented
    ///    in CHANGELOG.md, so an unintended template change can never cross a release.
    /// A fix applied to only one side breaks the "wizard output mirrors the canonical
    /// example" guarantee (NEXUS_READY Kapı 10) and silently ships the stale pattern
    /// to every new project.
    /// </summary>
    [TestFixture]
    public class WizardTemplateSyncTests
    {
        [Test]
        public void GeneratedFilesMapping_MatchesCanonicalSamples()
        {
            // The mapping is exactly what GenerateAllCode writes. Every entry must
            // resolve to a canonical Game/Samples file with identical content, so a
            // template can never be renamed, re-pathed, or orphaned without this test
            // failing. Paths are derived from the same GameRoot constant generation uses.
            foreach (var (relativePath, content) in NexusSetupWizard.GeneratedFiles())
            {
                string canonicalPath = Path.Combine(Application.dataPath, NexusSetupWizard.GameRoot, relativePath);
                Assert.IsTrue(File.Exists(canonicalPath),
                    $"Generated file '{relativePath}' has no canonical counterpart at '{canonicalPath}'. " +
                    "The Game/Samples dogfood example must exist for the sync contract to hold.");
                Assert.AreEqual(Normalize(content.Trim()), Normalize(File.ReadAllText(canonicalPath).Trim()),
                    $"Template for '{relativePath}' drifted from the canonical Game/Samples file. " +
                    "Apply the same change to both sides — the template lives in NexusSetupWizard.cs, " +
                    $"the canonical file in Assets/Scripts/Game/Samples/{relativePath}.");
            }
        }

        [Test]
        public void WriteGeneratedFiles_ProducesCanonicalBytes()
        {
            // Exercise the REAL generation write path (directory creation + File.WriteAllText)
            // into a temp root, then verify every written file is byte-identical
            // (line-ending normalized) to its template AND to the canonical sample, and
            // that the wizard writes nothing beyond the declared mapping.
            string tempRoot = Path.Combine(Path.GetTempPath(), "NexusWizardSync_" + Guid.NewGuid().ToString("N"));
            try
            {
                NexusSetupWizard.WriteGeneratedFiles(tempRoot);

                foreach (var (relativePath, content) in NexusSetupWizard.GeneratedFiles())
                {
                    string writtenPath = Path.Combine(tempRoot, relativePath.Replace('/', Path.DirectorySeparatorChar));
                    Assert.IsTrue(File.Exists(writtenPath),
                        $"GenerateAllCode mapping did not write '{relativePath}'.");

                    string written = Normalize(File.ReadAllText(writtenPath).Trim());
                    Assert.AreEqual(Normalize(content.Trim()), written,
                        $"Written file '{relativePath}' differs from its template.");

                    string canonicalPath = Path.Combine(Application.dataPath, NexusSetupWizard.GameRoot, relativePath);
                    Assert.AreEqual(Normalize(File.ReadAllText(canonicalPath).Trim()), written,
                        $"Generated bytes for '{relativePath}' differ from the canonical sample.");
                }

                string[] writtenFiles = Directory.GetFiles(tempRoot, "*", SearchOption.AllDirectories);
                Assert.AreEqual(NexusSetupWizard.GeneratedFiles().Count, writtenFiles.Length,
                    "The generator wrote files outside the declared template set.");
            }
            finally
            {
                if (Directory.Exists(tempRoot))
                    Directory.Delete(tempRoot, true);
            }
        }

        [Test]
        public void GeneratedFiles_CompileWithUnityRoslyn()
        {
            // The strongest check short of importing the files into the project: compile
            // the generated sources with the SAME Roslyn compiler Unity ships, against
            // the real UnityEngine.CoreModule / UnityEngine.UI / com.nexus.core reference
            // assemblies. Byte-equality with the canonical sample (tests above) proves
            // the two haven't drifted; this proves the wizard output actually BUILDS
            // against the framework APIs the generated code calls.
            string tempRoot = Path.Combine(Path.GetTempPath(), "NexusWizardCompile_" + Guid.NewGuid().ToString("N"));
            string outputDll = Path.Combine(Path.GetTempPath(), "NexusWizardCompileOut_" + Guid.NewGuid().ToString("N") + ".dll");
            try
            {
                NexusSetupWizard.WriteGeneratedFiles(tempRoot);

                string runner, compiler;
                Assert.IsTrue(TryFindRoslynCompiler(out runner, out compiler),
                    "Unity's bundled Roslyn compiler was not found under the editor's Data folder.");

                string[] references = ResolveCompileReferences();

                var startInfo = new ProcessStartInfo
                {
                    FileName = runner ?? compiler,
                    RedirectStandardOutput = true,
                    RedirectStandardError = true,
                    UseShellExecute = false,
                    CreateNoWindow = true
                };
                startInfo.ArgumentList.Add("-nologo");
                startInfo.ArgumentList.Add("-noconfig");
                startInfo.ArgumentList.Add("-nostdlib");
                startInfo.ArgumentList.Add("-target:library");
                startInfo.ArgumentList.Add("-out:" + outputDll);
                foreach (string reference in references)
                    startInfo.ArgumentList.Add("-r:" + reference);
                foreach (string file in Directory.GetFiles(tempRoot, "*.cs", SearchOption.AllDirectories))
                    startInfo.ArgumentList.Add(file);

                using (var process = Process.Start(startInfo))
                {
                    Assert.IsNotNull(process, "Failed to start the Unity Roslyn compiler.");
                    string stdout = process.StandardOutput.ReadToEnd();
                    string stderr = process.StandardError.ReadToEnd();
                    Assert.IsTrue(process.WaitForExit(120000), "Compiler timed out after 120s.");
                    Assert.AreEqual(0, process.ExitCode,
                        $"Generated files failed to compile (exit {process.ExitCode}).\nSTDOUT:\n{stdout}\nSTDERR:\n{stderr}");
                    Assert.IsTrue(File.Exists(outputDll),
                        $"Compiler reported success but produced no output assembly.{stdout}");
                }
            }
            finally
            {
                if (Directory.Exists(tempRoot))
                    Directory.Delete(tempRoot, true);
                if (File.Exists(outputDll))
                    File.Delete(outputDll);
            }
        }

        [Test]
        public void GeneratedFileHashes_MatchDocumentedChangelogValues()
        {
            // CHANGELOG.md documents each generated file's content hash in a table. An
            // intentional template change requires updating that table and the release
            // note; an unintentional one (stale template, silent drift) fails here. This
            // is the early-warning gate that catches a template change the moment it
            // happens — before it crosses a release boundary in the notes.
            string changelogPath = Path.Combine(Application.dataPath, "..", "CHANGELOG.md");
            Assert.IsTrue(File.Exists(changelogPath), $"CHANGELOG.md not found at '{changelogPath}'.");
            string changelog = File.ReadAllText(changelogPath);

            foreach (var (relativePath, hash) in NexusSetupWizard.GeneratedFileHashes())
            {
                string row = changelog
                    .Split('\n')
                    .FirstOrDefault(line => line.Contains(relativePath) && line.Contains("`" + hash + "`"));

                Assert.IsNotNull(row,
                    $"Generated file '{relativePath}' changed: its content hash (`{hash}`) is not documented in " +
                    "CHANGELOG.md. If the change is intentional, update the template-hash table and the " +
                    "release note for that template; if not, an unintended template edit slipped in.");
            }
        }

        [Test]
        public void GameMediatorTemplate_UsesTrackedSubscriptionPattern()
        {
            // Regression guard for the subscription-hygiene fix: the generated mediator
            // must remove its OWN handlers (RemoveOnChanged + event -=), never use
            // ClearOnChanged (which would wipe every other subscriber of the shared
            // model property), and never leak an anonymous event lambda.
            string template = NexusSetupWizard.GameMediatorTemplate;
            StringAssert.Contains("RemoveOnChanged", template);
            StringAssert.Contains("OnIncrementClicked -= OnIncrementClicked", template);
            StringAssert.DoesNotContain("ClearOnChanged", template);
            StringAssert.DoesNotContain("+= () => SignalBus.Fire", template);
        }

        /// <summary>
        /// Locates the C# compiler Unity ships with its editor data:
        /// - Unity 6+: dotnet-hosted Roslyn under <c>DotNetSdk/sdk/&lt;version&gt;/Roslyn/bincore/csc.dll</c>,
        ///   run via <c>DotNetSdk/dotnet(.exe)</c>;
        /// - Unity 2020-2022: mono-hosted Roslyn under <c>Tools/Roslyn/csc.exe</c>, run directly on
        ///   Windows and via <c>MonoBleedingEdge/bin/mono</c> on macOS/Linux.
        /// Returns false if neither is present (the test then fails with a clear message).
        /// </summary>
        private static bool TryFindRoslynCompiler(out string runner, out string compiler)
        {
            string contents = EditorApplication.applicationContentsPath;
            runner = null;
            compiler = null;

            string sdkRoot = Path.Combine(contents, "DotNetSdk");
            if (Directory.Exists(sdkRoot))
            {
                foreach (string sdk in Directory.GetDirectories(Path.Combine(sdkRoot, "sdk")))
                {
                    string csc = Path.Combine(sdk, "Roslyn", "bincore", "csc.dll");
                    if (!File.Exists(csc)) continue;
                    string dotnet = Path.Combine(sdkRoot,
                        Application.platform == RuntimePlatform.WindowsEditor ? "dotnet.exe" : "dotnet");
                    if (!File.Exists(dotnet)) continue;
                    runner = dotnet;
                    compiler = csc;
                    return true;
                }
            }

            string legacy = Path.Combine(contents, "Tools", "Roslyn", "csc.exe");
            if (File.Exists(legacy))
            {
                compiler = legacy;
                runner = Application.platform == RuntimePlatform.WindowsEditor
                    ? null // csc.exe runs directly on Windows
                    : Path.Combine(contents, "MonoBleedingEdge", "bin", "mono");
                return true;
            }
            return false;
        }

        /// <summary>
        /// The reference assemblies the generated files compile against: the netstandard 2.1
        /// reference assembly, <c>UnityEngine.CoreModule</c> (MonoBehaviour/SerializeField/UI
        /// events), and the project's own compiled <c>UnityEngine.UI</c> (uGUI) and
        /// <c>com.nexus.core</c> assemblies from <c>Library/ScriptAssemblies</c>. These exist
        /// whenever the test itself compiled, i.e. on any machine where the editor has ever
        /// built the project.
        /// </summary>
        private static string[] ResolveCompileReferences()
        {
            string contents = EditorApplication.applicationContentsPath;
            string scriptAssemblies = Path.Combine(Application.dataPath, "..", "Library", "ScriptAssemblies");

            var references = new List<string>
            {
                Path.Combine(contents, "NetStandard", "ref", "2.1.0", "netstandard.dll"),
                Path.Combine(contents, "Managed", "UnityEngine", "UnityEngine.CoreModule.dll"),
                Path.Combine(scriptAssemblies, "UnityEngine.UI.dll"),
                Path.Combine(scriptAssemblies, "com.nexus.core.dll")
            };

            foreach (string reference in references)
                Assert.IsTrue(File.Exists(reference),
                    $"Reference assembly not found: '{reference}'. Open the project in the Unity editor once so Library/ScriptAssemblies is populated.");
            return references.ToArray();
        }

        private static string Normalize(string s) => s.Replace("\r\n", "\n");
    }
}
