using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;
using UnityEditor;
using UnityEngine;
using Nexus.Core;

namespace Nexus.Editor
{
    public static class NexusCodeGenerator
    {
        [MenuItem("Nexus/Generate AOT Binder")]
        public static void GenerateBinder()
        {
            Debug.Log("[Nexus] Generating AOT Binder...");
            var injectTypes = new List<Type>();
            var networkSignalTypes = new List<Type>();
            
            // Gather all types containing [Inject] and all INetworkSignal implementations
            foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                var name = assembly.GetName().Name;
                if (name.StartsWith("System") || name.StartsWith("Unity") || name.StartsWith("Microsoft") || name.StartsWith("mono") || name.Contains("Test") || name.Contains("test"))
                    continue;

                try
                {
                    foreach (var type in assembly.GetTypes())
                    {
                        if (type.IsValueType && typeof(Nexus.Netcode.INetworkSignal).IsAssignableFrom(type))
                        {
                            networkSignalTypes.Add(type);
                        }

                        if (type.IsClass && !type.IsAbstract)
                        {
                            bool hasInject = false;
                            
                            var fields = type.GetFields(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
                            foreach (var f in fields)
                            {
                                if (f.GetCustomAttribute<InjectAttribute>() != null)
                                {
                                    hasInject = true;
                                    break;
                                }
                            }

                            if (!hasInject)
                            {
                                var properties = type.GetProperties(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
                                foreach (var p in properties)
                                {
                                    if (p.GetCustomAttribute<InjectAttribute>() != null)
                                    {
                                        hasInject = true;
                                        break;
                                    }
                                }
                            }

                            if (!hasInject)
                            {
                                var methods = type.GetMethods(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
                                foreach (var m in methods)
                                {
                                    if (m.GetCustomAttribute<InjectAttribute>() != null)
                                    {
                                        hasInject = true;
                                        break;
                                    }
                                }
                            }

                            if (hasInject)
                            {
                                injectTypes.Add(type);
                            }
                        }
                    }
                }
                catch (ReflectionTypeLoadException) { }
            }

            var sb = new StringBuilder();
            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     This code was generated by Nexus AOT Binder Code Generator.");
            sb.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
            sb.AppendLine("//     the code is regenerated.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using Nexus.Core;");
            sb.AppendLine("using Nexus.Netcode;");
            sb.AppendLine();
            sb.AppendLine("namespace Nexus.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    public static class NexusGeneratedBinder");
            sb.AppendLine("    {");
            sb.AppendLine("        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.SubsystemRegistration)]");
            sb.AppendLine("        public static void Initialize()");
            sb.AppendLine("        {");

            // Generate NetworkSignalBus CustomDispatcher
            if (networkSignalTypes.Count > 0)
            {
                sb.AppendLine("            NetworkSignalBus.CustomDispatcher = (bus, signal) =>");
                sb.AppendLine("            {");
                sb.AppendLine("                var type = signal.GetType();");
                foreach (var sigType in networkSignalTypes)
                {
                    string fullName = sigType.FullName.Replace("+", ".");
                    sb.AppendLine($"                if (type == typeof({fullName}))");
                    sb.AppendLine("                {");
                    sb.AppendLine($"                    bus.Fire(({fullName})signal);");
                    sb.AppendLine("                    return;");
                    sb.AppendLine("                }");
                }
                sb.AppendLine("            };");
                sb.AppendLine();
            }

            foreach (var type in injectTypes)
            {
                string fullName = type.FullName.Replace("+", "."); // handle nested classes
                sb.AppendLine($"            NexusDI.RegisterInjector<{fullName}>((instance, di) =>");
                sb.AppendLine("            {");

                // Inject Fields
                var fields = type.GetFields(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
                foreach (var f in fields)
                {
                    if (f.GetCustomAttribute<InjectAttribute>() != null && !f.FieldType.IsValueType)
                    {
                        if (f.IsPublic)
                        {
                            sb.AppendLine($"                instance.{f.Name} = di.Resolve<{f.FieldType.FullName.Replace("+", ".")}>();");
                        }
                        else
                        {
                            // Private field fallback via reflection, but compile-time cached / warning
                            sb.AppendLine($"                typeof({fullName}).GetField(\"{f.Name}\", System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance).SetValue(instance, di.Resolve<{f.FieldType.FullName.Replace("+", ".")}>());");
                        }
                    }
                }

                // Inject Properties
                var properties = type.GetProperties(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
                foreach (var p in properties)
                {
                    if (p.GetCustomAttribute<InjectAttribute>() != null && !p.PropertyType.IsValueType)
                    {
                        var setMethod = p.GetSetMethod(true);
                        if (setMethod != null)
                        {
                            if (setMethod.IsPublic)
                            {
                                sb.AppendLine($"                instance.{p.Name} = di.Resolve<{p.PropertyType.FullName.Replace("+", ".")}>();");
                            }
                            else
                            {
                                sb.AppendLine($"                typeof({fullName}).GetProperty(\"{p.Name}\", System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance).SetValue(instance, di.Resolve<{p.PropertyType.FullName.Replace("+", ".")}>());");
                            }
                        }
                    }
                }

                // Inject Methods
                var methods = type.GetMethods(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
                foreach (var m in methods)
                {
                    if (m.GetCustomAttribute<InjectAttribute>() != null)
                    {
                        bool hasValueTypeParams = false;
                        var paramList = new List<string>();
                        foreach (var p in m.GetParameters())
                        {
                            if (p.ParameterType.IsValueType)
                            {
                                hasValueTypeParams = true;
                                break;
                            }
                            paramList.Add($"di.Resolve<{p.ParameterType.FullName.Replace("+", ".")}>()");
                        }
                        
                        if (hasValueTypeParams) continue;

                        if (m.IsPublic)
                        {
                            sb.AppendLine($"                instance.{m.Name}({string.Join(", ", paramList)});");
                        }
                        else
                        {
                            sb.AppendLine($"                typeof({fullName}).GetMethod(\"{m.Name}\", System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance).Invoke(instance, new object[] {{ {string.Join(", ", paramList)} }});");
                        }
                    }
                }

                sb.AppendLine("            });");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        // Forces IL2CPP to preserve members that are injected");
            sb.AppendLine("        public static void PreserveMembers()");
            sb.AppendLine("        {");
            sb.AppendLine("            #pragma warning disable 0169, 0414, 0219");
            sb.AppendLine("            if (false)");
            sb.AppendLine("            {");

            foreach (var type in injectTypes)
            {
                string fullName = type.FullName.Replace("+", ".");
                
                var fields = type.GetFields(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
                foreach (var f in fields)
                {
                    if (f.GetCustomAttribute<InjectAttribute>() != null && f.IsPublic)
                    {
                        sb.AppendLine($"                var _f_{type.Name}_{f.Name} = default({fullName}).{f.Name};");
                    }
                }

                var properties = type.GetProperties(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
                foreach (var p in properties)
                {
                    if (p.GetCustomAttribute<InjectAttribute>() != null && p.GetMethod != null && p.GetMethod.IsPublic)
                    {
                        sb.AppendLine($"                var _p_{type.Name}_{p.Name} = default({fullName}).{p.Name};");
                    }
                }
            }

            sb.AppendLine("            }");
            sb.AppendLine("            #pragma warning restore 0169, 0414, 0219");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            string destFolder = "Assets/Scripts/Nexus";
            if (!Directory.Exists(destFolder))
            {
                Directory.CreateDirectory(destFolder);
            }

            string destFile = Path.Combine(destFolder, "NexusGeneratedBinder.g.cs");
            File.WriteAllText(destFile, sb.ToString());
            AssetDatabase.Refresh();
            Debug.Log($"[Nexus] AOT Binder successfully generated at {destFile}");
        }
    }
}
