<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>netstandard2.1</TargetFramework><LangVersion>latest</LangVersion><EnableDefaultCompileItems>false</EnableDefaultCompileItems><DefineConstants>$(DefineConstants);NOT_UNITY3D</DefineConstants><AssemblyName>VContainer</AssemblyName></PropertyGroup><ItemGroup><Compile Include="competitors/VContainer/VContainer/Assets/VContainer/Runtime/**/*.cs" Exclude="competitors/VContainer/VContainer/Assets/VContainer/Runtime/Unity/**/*.cs" /></ItemGroup></Project>